---
- name: My playbook for task3
  hosts: nodes
  tasks:
  - name: Adding net.ifnames=0 parameter to grub2 config
    lineinfile:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames)\"[^\"]+)(\".*)'
      line: '\1 net.ifnames=0\2'
      backrefs: yes
      state: present
  - name: Adding biosdevname=0 parameter to grub2 config
    lineinfile:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* biosdevname)\"[^\"]+)(\".*)'
      line: '\1 biosdevname=0\2'
      backrefs: yes
      state: present
  - name: Executing config generation
    command:
      cmd: grub2-mkconfig –o /boot/grub2/grub.cfg
...