---
- name: My playbook for task1
  hosts: nodes
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: latest
  - name: Ensure that httpd has started
    service: 
      name: httpd
      state: started
  - name: Write string to file
    copy:
      content: "Welcome to my web server"
      dest: /var/www/html/index.html
  - name: Check firewall for http
    firewalld:
      port: 80
      state: enabled
...