---
- name: My playbook for task2
  hosts: nodes
  tasks:
  - name: Remove httpd package
    yum:
      name: httpd
      state: absent
  - name: Delete index file for httpd service
    file:
      path: /var/www/html/index.html
      state: absent
  - name: Check firewall for http
    firewalld:
      service: http
      state: disabled
      permanent: true
  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted
...