---
- name: My playbook for task2
  hosts: nodes
  tasks:
  - name: Stop httpd service
    service:
      name: httpd
      state: stopped
  - name: Ensure that httpd service disabled
    service: 
      name: httpd
      enabled: no
  - name: Delete index file for httpd service
    file:
      path: /var/www/html/index.html
      state: absent
## in we need completely remove document root
#  - name: Remove document root for httpd service
#      file:
#        path: /var/www/html
#        state: absent
  - name: Remove httpd package
    yum:
      name: httpd
      state: absent
  - name: Check firewall for http
    firewalld:
      port: 80/tcp
      state: disabled
      permanent: true
...